version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: seckill-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seckill_db
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:6-alpine
    container_name: seckill-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: seckill-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest




